
export enum RouteName {
  /**
   * Admin
   */

  USER_LIST = 'USER_LIST',
  USER = 'USER',
  USER_PERMISSION = 'USER_PERMISSION',

  REPORT_LIST = 'REPORT_LIST',
  REPORT = 'REPORT',

  LOG_LIST = 'LOG_LIST',
  LOG = 'LOG',
  LOG_DETAILS = 'LOG_DETAILS',

  GENERAL = 'GENERAL',

  ROLE_LIST = 'ROLE_LIST',
  ROLE = 'ROLE',
  ROLE_PERMISSION = 'ROLE_PERMISSION',

  /**
   * Blog
   */

  BLOG = 'BLOG',

  POST = 'POST',
  POST_COMMENT = 'POST_COMMENT',

  CATEGORY = 'CATEGORY',
  CATEGORY_POST = 'CATEGORY_POST',

  /**
   * Home
   */

  DASHBOARD = 'DASHBOARD',

  PROFILE = 'PROFILE',

  SETTINGS = 'SETTINGS',
  ACCOUNT = 'ACCOUNT',
  SECURITY = 'SECURITY',
  NOTIFICATIONS = 'NOTIFICATIONS',

  PREFERENCES = 'PREFERENCES',
  THEME = 'THEME',
  LANGUAGE = 'LANGUAGE',

  /**
   * Products
   */

  PRODUCT_LIST = 'PRODUCT_LIST',

  CATEGOGY = 'CATEGOGY',

  PRODUCT = 'PRODUCT',
  REVIEW = 'REVIEW',
  REVIEW_COMMENT = 'REVIEW_COMMENT',

  REVIEW_COMPARE = 'REVIEW_COMPARE',
}
